### ISSUE TITLE
Cannot link executable

### ISSUE THREAD

**Issue by fhoshino** [cswl/tsu#57] opened 2020-05-08 07:44 UTC
Throws out the error below and terminates:
```
➜  ~ tsu
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "u_foldCase_58" referenced by "/system/lib64/libsqlite.so"...
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "u_foldCase_58" referenced by "/system/lib64/libsqlite.so"...
[1]    16255 abort      tsu
```

**Comment by cswl** [comment] 2020-05-08 08:44
Can you tell me which  root and which version of su are you using..

**Comment by fhoshino** [comment] 2020-05-08 08:47
20.3:MAGISKSU

**Comment by cswl** [comment] 2020-05-08 09:14
Can you run this command for me and post the output?
```
env | grep LD_ 
```

Also state the Android version..

Thanks for reporting

**Comment by fhoshino** [comment] 2020-05-08 09:17
```
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
```
Android 8.1

**Comment by cswl** [comment] 2020-05-08 09:56
@fhoshino 

Can you try this next version.
You can check it out with

```
curl -L "https://raw.githubusercontent.com/cswl/tsu/next/shell/tsu.sh"  > "$PREFIX/bin/tsu" 
```

**Comment by fhoshino** [comment] 2020-05-08 10:01
![Screenshot_20200508-180029](https://user-images.githubusercontent.com/771955/81395270-e648cd80-9155-11ea-97f2-f2aae1173b19.jpg)
Still getting the same error

**Comment by cswl** [comment] 2020-05-08 10:18
Download it again.. and this time run it with.. 

`tsu --D` to enable debug outputs..  

Sorry for the trouble.. but I dont have an Android 8.0 device

**Comment by fhoshino** [comment] 2020-05-08 10:20
```
➜  ~ tsu --D
+ TERMUX_FS=/data/data/com.termux/files
+ TERMUX_PREFIX=/data/data/com.termux/files/usr
+ TERMUX_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
+ ROOT_HOME=/data/data/com.termux/files/home/.suroot
+ ANDROIDSYSTEM_PATHS=/system/bin:/system/xbin
+ BB_MAGISK=/sbin/.magisk/busybox
+ [[ '' == true ]]
+ [[ -z '' ]]
+ SWITCH_USER=
+ declare -A EXP_ENV
+ root_shell_helper
+ '[' '' = system ']'
+ '[' -n '' ']'
+ test -x /data/data/com.termux/files/home/.termux/shell
++ readlink -f -- /data/data/com.termux/files/home/.termux/shell
+ ROOT_SHELL=/data/data/com.termux/files/usr/bin/zsh
+ [[ '' == true ]]
+ STARTUP_SCRIPT=/data/data/com.termux/files/usr/bin/zsh
+ SU_BINARY_SEARCH=("/system/xbin/su" "/system/bin/su")
+ [[ -x /sbin ]]
+ SU_BINARY_SEARCH+=("/sbin/su" "/sbin/bin/su")
+ [[ -z '' ]]
++ /sbin/su -v
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "u_foldCase_58" referenced by "/system/lib64/libsqlite.so"...
+ [[ '' == *\M\A\G\I\S\K\S\U ]]
+ for SU_BINARY in "${SU_BINARY_SEARCH[@]}"
+ '[' -e /system/xbin/su ']'
+ for SU_BINARY in "${SU_BINARY_SEARCH[@]}"
+ '[' -e /system/bin/su ']'
+ for SU_BINARY in "${SU_BINARY_SEARCH[@]}"
+ '[' -e /sbin/su ']'
+ exec /sbin/su -c '/system/bin/env -i  /data/data/com.termux/files/usr/bin/zsh'
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "u_foldCase_58" referenced by "/system/lib64/libsqlite.so"...
[1]    10075 abort      tsu --D
```

**Comment by cswl** [comment] 2020-05-09 05:57
Please try this version..

The new command to debug is `tsu --dbg`
```
curl -L "https://raw.githubusercontent.com/cswl/tsu/next/dist/tsu"  > "$PREFIX/bin/tsu"
```

**Comment by fhoshino** [comment] 2020-05-09 06:00
```
➜  ~ tsu --dbg
+ TERMUX_FS=/data/data/com.termux/files
+ TERMUX_PREFIX=/data/data/com.termux/files/usr
+ TERMUX_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
+ ROOT_HOME=/data/data/com.termux/files/home/.suroot
+ ANDROIDSYSTEM_PATHS=/system/bin:/system/xbin
+ BB_MAGISK=/sbin/.magisk/busybox
+ [[ '' == true ]]
+ [[ -z '' ]]
+ SWITCH_USER=
+ declare -A EXP_ENV
+ root_shell_helper
+ '[' '' = system ']'
+ '[' -n '' ']'
+ test -x /data/data/com.termux/files/home/.termux/shell
++ readlink -f -- /data/data/com.termux/files/home/.termux/shell
+ ROOT_SHELL=/data/data/com.termux/files/usr/bin/zsh
+ env_path_helper
+ [[ -z '' ]]
+ NEW_HOME=/data/data/com.termux/files/home/.suroot
+ EXP_ENV[PREFIX]=/data/data/com.termux/files/usr
+ EXP_ENV[TMPDIR]=/data/data/com.termux/files/home/.suroot/.tmp
+ EXP_ENV[LD_PRELOAD]=/data/data/com.termux/files/usr/lib/libtermux-exec.so
+ NEW_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
+ ASP=/system/bin:/system/xbin
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n /data/data/com.termux/files/usr/lib ]]
+ SYS_LIBS=/system/lib64
+ EXP_ENV[LD_LIBRARY_PATH]=/data/data/com.termux/files/usr/lib:/system/lib64
+ EXP_ENV[PATH]=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
+ EXP_ENV[HOME]=/data/data/com.termux/files/home/.suroot
+ EXP_ENV[TERM]=xterm-256color
+ [[ -z true ]]
+ set +x
+ [[ '' == true ]]
+ STARTUP_SCRIPT=/data/data/com.termux/files/usr/bin/zsh
+ SU_BINARY_SEARCH=("/system/xbin/su" "/system/bin/su")
+ [[ -x /sbin ]]
+ SU_BINARY_SEARCH+=("/sbin/su" "/sbin/bin/su")
+ [[ -z '' ]]
++ /sbin/su -v
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "u_foldCase_58" referenced by "/system/lib64/libsqlite.so"...
+ [[ '' == *\M\A\G\I\S\K\S\U ]]
+ for SU_BINARY in "${SU_BINARY_SEARCH[@]}"
+ '[' -e /system/xbin/su ']'
+ for SU_BINARY in "${SU_BINARY_SEARCH[@]}"
+ '[' -e /system/bin/su ']'
+ for SU_BINARY in "${SU_BINARY_SEARCH[@]}"
+ '[' -e /sbin/su ']'
+ exec /sbin/su -c '/system/bin/env -i  PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets  LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib:/system/lib64  ANDROID_DATA=/data  TMPDIR=/data/data/com.termux/files/home/.suroot/.tmp  PREFIX=/data/data/com.termux/files/usr  TERM=xterm-256color  LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so  ANDROID_ROOT=/system  HOME=/data/data/com.termux/files/home/.suroot  /data/data/com.termux/files/usr/bin/zsh'
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "u_foldCase_58" referenced by "/system/lib64/libsqlite.so"...
[1]    29153 abort      tsu --dbg
```

**Comment by cswl** [comment] 2020-05-09 07:29
Updated one more time.. here it goes..

`curl -L "https://raw.githubusercontent.com/cswl/tsu/next/dist/tsu"  > "$PREFIX/bin/tsu"`

Unsetted everything .. we arent even using LD_*  in any version

**Comment by fhoshino** [comment] 2020-05-09 07:33
```
➜  ~ tsu
+ [[ '' == true ]]
+ STARTUP_SCRIPT=/data/data/com.termux/files/usr/bin/zsh
+ SU_BINARY_SEARCH=("/system/xbin/su" "/system/bin/su")
+ [[ -x /sbin ]]
+ SU_BINARY_SEARCH+=("/sbin/su" "/sbin/bin/su")
+ unset LD_LIBRARY_PATH
+ unset LD_PRELOAD
+ [[ -z '' ]]
++ /sbin/su -v
+ [[ 20.3:MAGISKSU == *\M\A\G\I\S\K\S\U ]]
+ exec /sbin/su -c 'PATH=/sbin/.magisk/busybox env -i  PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets  ANDROID_DATA=/data  TMPDIR=/data/data/com.termux/files/home/.suroot/.tmp  PREFIX=/data/data/com.termux/files/usr  TERM=xterm-256color  LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so  ANDROID_ROOT=/system  HOME=/data/data/com.termux/files/home/.suroot  /data/data/com.termux/files/usr/bin/zsh'
#
```
Got root, but not in default shell

**Comment by cswl** [comment] 2020-05-09 08:41
Can you run with `tsu --dbg` again...
Im sure I also exported LD_LIBRARY_PATH

**Comment by fhoshino** [comment] 2020-05-09 08:48
```
➜  ~ tsu --dbg                                                + TERMUX_FS=/data/data/com.termux/files
+ TERMUX_PREFIX=/data/data/com.termux/files/usr
+ TERMUX_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
+ ROOT_HOME=/data/data/com.termux/files/home/.suroot
+ ANDROIDSYSTEM_PATHS=/system/bin:/system/xbin
+ BB_MAGISK=/sbin/.magisk/busybox
+ [[ '' == true ]]
+ [[ -z '' ]]
+ SWITCH_USER=
+ declare -A EXP_ENV
+ root_shell_helper
+ '[' '' = system ']'
+ '[' -n '' ']'
+ test -x /data/data/com.termux/files/home/.termux/shell
++ readlink -f -- /data/data/com.termux/files/home/.termux/shell
+ ROOT_SHELL=/data/data/com.termux/files/usr/bin/zsh
+ env_path_helper
+ [[ -z '' ]]
+ NEW_HOME=/data/data/com.termux/files/home/.suroot
+ EXP_ENV[PREFIX]=/data/data/com.termux/files/usr
+ EXP_ENV[TMPDIR]=/data/data/com.termux/files/home/.suroot/.tmp
+ EXP_ENV[LD_PRELOAD]=/data/data/com.termux/files/usr/lib/libtermux-exec.so
+ NEW_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
+ ASP=/system/bin:/system/xbin
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ log_debug 'LD_LIBRARY_PATH not set.'
+ :
+ EXP_ENV[PATH]=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
+ EXP_ENV[HOME]=/data/data/com.termux/files/home/.suroot
+ EXP_ENV[TERM]=xterm-256color
+ [[ -z true ]]
+ set +x
+ [[ '' == true ]]
+ STARTUP_SCRIPT=/data/data/com.termux/files/usr/bin/zsh
+ SU_BINARY_SEARCH=("/system/xbin/su" "/system/bin/su")
+ [[ -x /sbin ]]
+ SU_BINARY_SEARCH+=("/sbin/su" "/sbin/bin/su")
+ unset LD_LIBRARY_PATH
+ unset LD_PRELOAD
+ [[ -z '' ]]
++ /sbin/su -v
+ [[ 20.3:MAGISKSU == *\M\A\G\I\S\K\S\U ]]
+ exec /sbin/su -c 'PATH=/sbin/.magisk/busybox env -i  PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets  ANDROID_DATA=/data  TMPDIR=/data/data/com.termux/files/home/.suroot/.tmp  PREFIX=/data/data/com.termux/files/usr  TERM=xterm-256color  LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so  ANDROID_ROOT=/system  HOME=/data/data/com.termux/files/home/.suroot  /data/data/com.termux/files/usr/bin/zsh'
#
```

**Comment by cswl** [comment] 2020-05-09 11:03
`log_debug 'LD_LIBRARY_PATH not set.'`

This is really strange.. there should be "$LD_LIBRARY_PATH" exported for shell scripts..

Can you run this command..
`bash -c 'echo  "$LD_LIBRARY_PATH" '  `

Also after you run `tsu` do this to check if its actually zsh.. 
When you drop in a root shell the HOME is set to `~/.suroot`  like in actual `sudo` from gnu/linux

`echo $0`

**Comment by fhoshino** [comment] 2020-05-09 11:06
Got an empty response on `bash -c 'echo "$LD_LIBRARY_PATH" '`
```
# echo $0
/data/data/com.termux/files/usr/bin/zsh
```

**Comment by cswl** [comment] 2020-05-09 12:00
So zsh is running can you check, if any Termux programs.. run?

**Comment by fhoshino** [comment] 2020-05-09 12:02
I guess, yes?
![mintty_2020-05-09_20-02-14](https://user-images.githubusercontent.com/771955/81473298-0baa0a00-9230-11ea-8044-99ba66cbd300.png)

**Comment by cswl** [comment] 2020-05-09 12:12
Woah.. you ran tmux as root .

I'm resolving this issue as solved for now...
If you encounter any other issues let me know on another one.

**Closed by cswl** 2020-05-09 12:12 UTC

**Comment by fhoshino** [comment] 2020-05-09 12:26
But the shell is sticked to bash, is there a way to change back to my default shell?

**Comment by cswl** [comment] 2020-05-09 12:38
Hmm `$0` says zsh.. 

If youre actually running on zsh.. the below command should say `zsh`

`echo $ZSH_NAME`

**Comment by fhoshino** [comment] 2020-05-09 12:43
I guess it's wrap around zsh thus echo $ZSH_NAME shows zsh?
coz calling tmux in it clearly indicates it is bash, and also all my zshrc are not loaded.
manually typed "zsh" in it just calls bash again and nothing happened.

**Comment by cswl** [comment] 2020-05-09 13:06
You will need to copy your .zshrc and .tmux.conf and all others to `$HOME` of root.

This is intended behavior. and how this works in Linux too.

This is to prevent your normal user home directory for being owned by root.

I can confirm tmux will start bash at first.. but running zsh changes it to zsh..

Maybe we need to add default shell in tmux.conf of root

**Comment by fhoshino** [comment] 2020-05-09 13:21
I know how root works on regular linux, but what is the root's home in termux?
Previously tsu just uses the namespace's home so everything loads.
```
# cd ~
cd: no such file or directory: /data/data/com.termux/files/home/.suroot
# cat .suroot
cat: .suroot: No such file or directory
```

**Comment by cswl** [comment] 2020-05-09 13:34
Ah shit.. balls.. I forgot to create "$HOME/.suroot" if it doesn't exist.

The decision was made to prevent weird permission isues while running termux normally.

You can do this in normal termux..  for the time being.

`mkdir ~/.suroot`

**Comment by fhoshino** [comment] 2020-05-09 13:38
![ConEmu64_2020-05-09_21-38-22](https://user-images.githubusercontent.com/771955/81475219-6d24a580-923d-11ea-83f9-66a641e83b7a.png)
Nice.

**Comment by cswl** [comment] 2020-05-09 14:13
Sorry for all this trouble.

But newer Android versions.. needed some work to support .. 
And I dont have old device anymore
